"""finance_tax_foundation

Tax configuration as dated data (tax_config_entries, revisions, pack applications), the
organization's own registrations, finance settings, customer tax profiles, frozen per-line
taxes (document_tax_lines), TDS receivables and write-offs, plus the columns documents need.

Existing data keeps working: invoice and quotation taxes become document_tax_lines, and
credits are moved out of amount_settled (where the old credit-note code put them, marking
invoices "paid") into credited_amount.

Revision ID: a3f1c7d9e2b4
Revises: a7d3c9e1f5b2
Create Date: 2026-10-09 06:05:22.698953+00:00

"""
from decimal import ROUND_HALF_UP, Decimal
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
import database.types
from sqlalchemy.dialects import mysql

revision: str = 'a3f1c7d9e2b4'
down_revision: Union[str, None] = 'a7d3c9e1f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tax_lines',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('behaviour', sa.String(length=20), nullable=False),
    sa.Column('rate_code', sa.String(length=100), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('return_box', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_tax_lines_document', 'document_tax_lines', ['document_type', 'document_id'], unique=False)
    op.create_table('finance_settings',
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('billing_mode', sa.String(length=20), nullable=False),
    sa.Column('invoice_requires_schedule', sa.Boolean(), nullable=False),
    sa.Column('credit_note_deadline_mode', sa.String(length=20), nullable=False),
    sa.Column('collections_on_net', sa.Boolean(), nullable=False),
    sa.Column('default_payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_start', sa.String(length=5), nullable=True),
    sa.Column('default_tax_category', sa.String(length=100), nullable=True),
    sa.Column('deductee_type', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', database.types.UUIDType(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('org_tax_registrations',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('regime_code', sa.String(length=40), nullable=False),
    sa.Column('registration_no', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('trade_name', sa.String(length=512), nullable=True),
    sa.Column('jurisdiction_code', sa.String(length=20), nullable=True),
    sa.Column('registration_type', sa.String(length=40), nullable=False),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('lut_number', sa.String(length=100), nullable=True),
    sa.Column('lut_valid_from', sa.Date(), nullable=True),
    sa.Column('lut_valid_to', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'regime_code', 'registration_no', name='uq_org_tax_registrations_number')
    )
    op.create_index(op.f('ix_org_tax_registrations_organization_id'), 'org_tax_registrations', ['organization_id'], unique=False)
    op.create_table('tax_config_entries',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=60), nullable=False),
    sa.Column('locally_modified', sa.Boolean(), nullable=False),
    sa.Column('created_by', database.types.UUIDType(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kind', 'code', 'effective_from', name='uq_tax_config_entries_key')
    )
    op.create_index('ix_tax_config_entries_org_kind', 'tax_config_entries', ['organization_id', 'kind'], unique=False)
    op.create_table('tax_config_revisions',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('changed_by', database.types.UUIDType(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'revision', name='uq_tax_config_revisions_org_revision')
    )
    op.create_index(op.f('ix_tax_config_revisions_organization_id'), 'tax_config_revisions', ['organization_id'], unique=False)
    op.create_table('tax_pack_applications',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('pack_code', sa.String(length=60), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('applied_by', database.types.UUIDType(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_pack_applications_organization_id'), 'tax_pack_applications', ['organization_id'], unique=False)
    op.create_table('client_tax_profiles',
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('registration_type', sa.String(length=40), nullable=True),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('place_of_supply', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('tds_section_code', sa.String(length=100), nullable=True),
    sa.Column('lower_deduction_certificates', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', database.types.UUIDType(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_client_tax_profiles_organization_id'), 'client_tax_profiles', ['organization_id'], unique=False)
    op.create_table('invoice_write_offs',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('invoice_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('written_off_on', sa.Date(), nullable=False),
    sa.Column('created_by', database.types.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_write_offs_invoice_id'), 'invoice_write_offs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_write_offs_organization_id'), 'invoice_write_offs', ['organization_id'], unique=False)
    op.create_table('tds_receivables',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('payment_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('allocation_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('invoice_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('section_code', sa.String(length=100), nullable=True),
    sa.Column('statute_ref', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deducted_on', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('certificate_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['payment_allocations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_receivables_client_id'), 'tds_receivables', ['client_id'], unique=False)
    op.create_index(op.f('ix_tds_receivables_invoice_id'), 'tds_receivables', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_tds_receivables_organization_id'), 'tds_receivables', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tds_receivables_payment_id'), 'tds_receivables', ['payment_id'], unique=False)
    op.create_index(op.f('ix_tds_receivables_status'), 'tds_receivables', ['status'], unique=False)
    op.add_column('billing_schedule_lines', sa.Column('percent', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('billing_schedule_lines', sa.Column('payment_term_id', database.types.UUIDType(length=36), nullable=True))
    op.add_column('billing_schedule_lines', sa.Column('status', sa.String(length=20), nullable=False, server_default='planned'))
    op.add_column('billing_schedule_lines', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_billing_schedule_lines_status'), 'billing_schedule_lines', ['status'], unique=False)
    op.add_column('billing_schedules', sa.Column('basis_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('invoice_lines', sa.Column('tax_category_code', sa.String(length=100), nullable=True))
    op.add_column('invoice_lines', sa.Column('tax_rate', sa.Numeric(precision=9, scale=4), nullable=True))
    op.add_column('invoice_series', sa.Column('scope_key', sa.String(length=36), nullable=False, server_default='organization'))
    op.add_column('invoice_series', sa.Column('format', sa.String(length=100), nullable=True))
    op.alter_column('invoice_series', 'fin_registration_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_unique_constraint('uq_invoice_series_scope', 'invoice_series', ['organization_id', 'scope_key', 'doc_type', 'fiscal_year'])
    op.add_column('invoices', sa.Column('tax_registration_id', database.types.UUIDType(length=36), nullable=True))
    op.add_column('invoices', sa.Column('supplier_snapshot', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('supply_type', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('tax_point_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('round_off', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('config_revision', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('tax_notes', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('withholding', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('expected_withholding', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('credited_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('written_off_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('schedule_line_id', database.types.UUIDType(length=36), nullable=True))
    op.add_column('invoices', sa.Column('note_reason', sa.String(length=40), nullable=True))
    op.add_column('invoices', sa.Column('note_text', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('deadline_override_reason', sa.Text(), nullable=True))
    op.drop_index(op.f('uq_invoices_org_invoice_no'), table_name='invoices')
    op.create_index(op.f('ix_invoices_tax_registration_id'), 'invoices', ['tax_registration_id'], unique=False)
    op.create_unique_constraint('uq_invoices_org_gstin_invoice_no', 'invoices', ['organization_id', 'supplier_gstin', 'invoice_no'])
    op.create_unique_constraint('uq_invoices_schedule_line_id', 'invoices', ['schedule_line_id'])
    op.add_column('offerings', sa.Column('tax_category_code', sa.String(length=100), nullable=True))
    op.add_column('payment_allocations', sa.Column('tds_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('payment_allocations', sa.Column('tds_section_code', sa.String(length=100), nullable=True))
    op.add_column('payment_allocations', sa.Column('gst_tds_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('payments', sa.Column('tds_amount', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('quotation_items', sa.Column('tax_category_code', sa.String(length=100), nullable=True))
    op.add_column('quotations', sa.Column('tax_registration_id', database.types.UUIDType(length=36), nullable=True))
    op.add_column('quotations', sa.Column('supply_type', sa.String(length=20), nullable=True))
    op.add_column('quotations', sa.Column('config_revision', sa.Integer(), nullable=True))
    op.add_column('quotations', sa.Column('round_off', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0'))
    op.add_column('quotations', sa.Column('tax_notes', sa.JSON(), nullable=True))
    op.add_column('quotations', sa.Column('withholding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###
    _backfill(op.get_bind())


def downgrade() -> None:
    # Put credits back where the old code kept them (inside amount_settled).
    op.execute("UPDATE invoices SET amount_settled = amount_settled + credited_amount WHERE credited_amount > 0")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'withholding')
    op.drop_column('quotations', 'tax_notes')
    op.drop_column('quotations', 'round_off')
    op.drop_column('quotations', 'config_revision')
    op.drop_column('quotations', 'supply_type')
    op.drop_column('quotations', 'tax_registration_id')
    op.drop_column('quotation_items', 'tax_category_code')
    op.drop_column('payments', 'tds_amount')
    op.drop_column('payment_allocations', 'gst_tds_amount')
    op.drop_column('payment_allocations', 'tds_section_code')
    op.drop_column('payment_allocations', 'tds_amount')
    op.drop_column('offerings', 'tax_category_code')
    op.drop_constraint('uq_invoices_schedule_line_id', 'invoices', type_='unique')
    op.drop_constraint('uq_invoices_org_gstin_invoice_no', 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_tax_registration_id'), table_name='invoices')
    op.create_index(op.f('uq_invoices_org_invoice_no'), 'invoices', ['organization_id', 'invoice_no'], unique=True)
    op.drop_column('invoices', 'deadline_override_reason')
    op.drop_column('invoices', 'note_text')
    op.drop_column('invoices', 'note_reason')
    op.drop_column('invoices', 'schedule_line_id')
    op.drop_column('invoices', 'written_off_amount')
    op.drop_column('invoices', 'credited_amount')
    op.drop_column('invoices', 'expected_withholding')
    op.drop_column('invoices', 'withholding')
    op.drop_column('invoices', 'tax_notes')
    op.drop_column('invoices', 'config_revision')
    op.drop_column('invoices', 'round_off')
    op.drop_column('invoices', 'tax_point_date')
    op.drop_column('invoices', 'supply_type')
    op.drop_column('invoices', 'supplier_snapshot')
    op.drop_column('invoices', 'tax_registration_id')
    op.drop_constraint('uq_invoice_series_scope', 'invoice_series', type_='unique')
    op.execute("DELETE FROM invoice_series WHERE fin_registration_id IS NULL")
    op.alter_column('invoice_series', 'fin_registration_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('invoice_series', 'format')
    op.drop_column('invoice_series', 'scope_key')
    op.drop_column('invoice_lines', 'tax_rate')
    op.drop_column('invoice_lines', 'tax_category_code')
    op.drop_column('billing_schedules', 'basis_amount')
    op.drop_index(op.f('ix_billing_schedule_lines_status'), table_name='billing_schedule_lines')
    op.drop_column('billing_schedule_lines', 'version')
    op.drop_column('billing_schedule_lines', 'status')
    op.drop_column('billing_schedule_lines', 'payment_term_id')
    op.drop_column('billing_schedule_lines', 'percent')
    # Dropping a table drops its indexes; MySQL refuses to drop an index a foreign key still needs.
    op.drop_table('tds_receivables')
    op.drop_table('invoice_write_offs')
    op.drop_table('client_tax_profiles')
    op.drop_index(op.f('ix_tax_pack_applications_organization_id'), table_name='tax_pack_applications')
    op.drop_table('tax_pack_applications')
    op.drop_index(op.f('ix_tax_config_revisions_organization_id'), table_name='tax_config_revisions')
    op.drop_table('tax_config_revisions')
    op.drop_index('ix_tax_config_entries_org_kind', table_name='tax_config_entries')
    op.drop_table('tax_config_entries')
    op.drop_index(op.f('ix_org_tax_registrations_organization_id'), table_name='org_tax_registrations')
    op.drop_table('org_tax_registrations')
    op.drop_table('finance_settings')
    op.drop_index('ix_document_tax_lines_document', table_name='document_tax_lines')
    op.drop_table('document_tax_lines')
    # ### end Alembic commands ###


# ---------------------------------------------------------------- data

CENT = Decimal("0.01")
# How the code before this migration taxed documents: a GST split by comparing the place of
# supply with a fixed supplier state. Reproduced here only to describe existing quotations.
_LEGACY_SUPPLIER_STATE = "29"
_COMPONENTS = {
    "cgst": ("CGST", "Central GST"),
    "sgst": ("SGST", "State GST"),
    "igst": ("IGST", "Integrated GST"),
}


def _money(value) -> Decimal:
    return Decimal(str(value or 0)).quantize(CENT, rounding=ROUND_HALF_UP)


def _rate(amount: Decimal, base: Decimal) -> Decimal:
    if base == 0:
        return Decimal(0)
    return (amount * 100 / base).quantize(CENT, rounding=ROUND_HALF_UP)


def _tax_line(org_id, document_type, document_id, line_no, box, rate, base, amount) -> dict:
    code, label = _COMPONENTS[box]
    return {
        "id": str(uuid.uuid4()), "organization_id": str(org_id), "document_type": document_type,
        "document_id": str(document_id), "line_no": line_no, "component_code": code, "label": label,
        "behaviour": "added", "rate_code": None, "rate_percent": rate, "base_amount": base, "tax_amount": amount,
        "rule_code": "MIGRATED", "return_box": box,
    }


def _backfill(connection) -> None:
    tax_lines = sa.table(
        "document_tax_lines",
        *(sa.column(name) for name in (
            "id", "organization_id", "document_type", "document_id", "line_no", "component_code", "label", "behaviour",
            "rate_code", "rate_percent", "base_amount", "tax_amount", "rule_code", "return_box",
        )),
    )
    rows: list[dict] = []

    connection.execute(sa.text(
        "UPDATE invoice_series SET scope_key = fin_registration_id WHERE fin_registration_id IS NOT NULL"
    ))
    connection.execute(sa.text("UPDATE invoices SET tax_point_date = issue_date WHERE issue_date IS NOT NULL"))
    connection.execute(sa.text("UPDATE invoices SET supply_type = 'inter_state' WHERE igst_total > 0"))
    connection.execute(sa.text("UPDATE invoices SET supply_type = 'intra_state' WHERE igst_total = 0 AND cgst_total > 0"))

    # Invoice lines: their stored CGST/SGST/IGST become frozen tax lines; the rate is read back from them.
    invoice_lines = connection.execute(sa.text(
        "SELECT l.id, l.invoice_id, l.line_no, l.taxable_value, l.cgst_amount, l.sgst_amount, l.igst_amount, i.organization_id "
        "FROM invoice_lines l JOIN invoices i ON i.id = l.invoice_id"
    )).all()
    for line_id, invoice_id, line_no, taxable, cgst, sgst, igst, org_id in invoice_lines:
        base = _money(taxable)
        total = Decimal(0)
        for box, amount in (("cgst", _money(cgst)), ("sgst", _money(sgst)), ("igst", _money(igst))):
            if amount:
                rows.append(_tax_line(org_id, "invoice", invoice_id, line_no, box, _rate(amount, base), base, amount))
                total += amount
        connection.execute(
            sa.text("UPDATE invoice_lines SET tax_rate = :rate WHERE id = :id"), {"rate": _rate(total, base), "id": line_id}
        )

    # Quotation items stored only a rate and the place of supply.
    items = connection.execute(sa.text(
        "SELECT q.id, q.place_of_supply, c.organization_id, it.line_no, it.net_price, it.gst_rate "
        "FROM quotation_items it JOIN quotations q ON q.id = it.quotation_id JOIN clients c ON c.id = q.client_id"
    )).all()
    supply_types: dict[str, str] = {}
    for quote_id, place, org_id, line_no, net_price, gst_rate in items:
        base, rate = _money(net_price), Decimal(str(gst_rate or 0))
        if rate == 0:
            continue
        if (place or _LEGACY_SUPPLIER_STATE) == _LEGACY_SUPPLIER_STATE:
            half_rate = rate / 2
            half = (base * half_rate / 100).quantize(CENT, rounding=ROUND_HALF_UP)
            rows.append(_tax_line(org_id, "quotation", quote_id, line_no, "cgst", half_rate, base, half))
            rows.append(_tax_line(org_id, "quotation", quote_id, line_no, "sgst", half_rate, base, half))
            supply_types[quote_id] = "intra_state"
        else:
            amount = (base * rate / 100).quantize(CENT, rounding=ROUND_HALF_UP)
            rows.append(_tax_line(org_id, "quotation", quote_id, line_no, "igst", rate, base, amount))
            supply_types[quote_id] = "inter_state"
    for quote_id, supply_type in supply_types.items():
        connection.execute(sa.text("UPDATE quotations SET supply_type = :kind WHERE id = :id"), {"kind": supply_type, "id": quote_id})

    if rows:
        op.bulk_insert(tax_lines, rows)

    # Credits: the old code added a credit note to the original's amount_settled (and marked it
    # paid). Credits are now their own amount, and credit notes owe nothing themselves.
    credited = connection.execute(sa.text(
        "SELECT original_invoice_id, SUM(grand_total) FROM invoices "
        "WHERE doc_type = 'credit_note' AND original_invoice_id IS NOT NULL GROUP BY original_invoice_id"
    )).all()
    for original_id, credit_total in credited:
        original = connection.execute(
            sa.text("SELECT grand_total, amount_settled, status FROM invoices WHERE id = :id"), {"id": original_id}
        ).first()
        if original is None:
            continue
        grand_total, settled, status = _money(original[0]), _money(original[1]), original[2]
        credit = _money(credit_total)
        paid = max(settled - credit, Decimal(0))
        balance = max(grand_total - paid - credit, Decimal(0))
        if credit >= grand_total:
            status = "cancelled"
        elif balance == 0:
            status = "paid" if paid > 0 else "cancelled"
        elif paid > 0:
            status = "partially_paid"
        elif status != "overdue":
            status = "issued"
        connection.execute(
            sa.text(
                "UPDATE invoices SET credited_amount = :credit, amount_settled = :paid, balance_due = :balance, "
                "status = :status WHERE id = :id"
            ),
            {"credit": credit, "paid": paid, "balance": balance, "status": status, "id": original_id},
        )
    connection.execute(sa.text(
        "UPDATE invoices SET amount_settled = 0, balance_due = 0 WHERE doc_type = 'credit_note'"
    ))
