"""initial_revenue_tables

Revision ID: 0946d05b0fba
Revises: 
Create Date: 2026-09-22 04:16:11.616140+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database.types


revision: str = '0946d05b0fba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'accounting_exports' in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_exports',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('target_system', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_exports_entity_id'), 'accounting_exports', ['entity_id'], unique=False)
    op.create_index(op.f('ix_accounting_exports_organization_id'), 'accounting_exports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_accounting_exports_status'), 'accounting_exports', ['status'], unique=False)
    op.create_table('activities',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('outcome_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_organization_id'), 'activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_activities_owner_user_id'), 'activities', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_activities_subject_id'), 'activities', ['subject_id'], unique=False)
    op.create_table('billing_schedules',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('context_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_schedules_client_id'), 'billing_schedules', ['client_id'], unique=False)
    op.create_index(op.f('ix_billing_schedules_context_id'), 'billing_schedules', ['context_id'], unique=False)
    op.create_index(op.f('ix_billing_schedules_organization_id'), 'billing_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_billing_schedules_status'), 'billing_schedules', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=512), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_owner_user_id'), 'clients', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_clients_pan'), 'clients', ['pan'], unique=False)
    op.create_table('collection_cases',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dunning_level', sa.Integer(), nullable=False),
    sa.Column('total_overdue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('promised_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_cases_client_id'), 'collection_cases', ['client_id'], unique=False)
    op.create_index(op.f('ix_collection_cases_organization_id'), 'collection_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_collection_cases_owner_user_id'), 'collection_cases', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_collection_cases_status'), 'collection_cases', ['status'], unique=False)
    op.create_table('deals',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_organization_id'), 'deals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deals_owner_user_id'), 'deals', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('invoice_series',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('fin_registration_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_series_fin_registration_id'), 'invoice_series', ['fin_registration_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('vertical_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_ref', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('loss_reason', sa.String(length=512), nullable=True),
    sa.Column('scope_path', sa.String(length=2048), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_owner_user_id'), 'leads', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_leads_scope_path'), 'leads', ['scope_path'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_vertical_id'), 'leads', ['vertical_id'], unique=False)
    op.create_table('offerings',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('vertical_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sac_code', sa.String(length=20), nullable=True),
    sa.Column('gst_code', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('billing_model', sa.String(length=50), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('default_work_template_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offerings_code'), 'offerings', ['code'], unique=False)
    op.create_index(op.f('ix_offerings_organization_id'), 'offerings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_offerings_vertical_id'), 'offerings', ['vertical_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('receipt_no', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('bank_reference', sa.String(length=255), nullable=True),
    sa.Column('charges', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unapplied_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recorded_by', database.types.UUIDType(length=36), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_receipt_no'), 'payments', ['receipt_no'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('webhook_inbox',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_inbox_provider'), 'webhook_inbox', ['provider'], unique=False)
    op.create_index(op.f('ix_webhook_inbox_provider_event_id'), 'webhook_inbox', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_webhook_inbox_status'), 'webhook_inbox', ['status'], unique=False)
    op.create_table('client_contacts',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('contact_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_email'), 'client_contacts', ['email'], unique=False)
    op.create_table('collection_followups',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('case_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('by_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=255), nullable=True),
    sa.Column('followed_up_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['collection_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_followups_case_id'), 'collection_followups', ['case_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('series_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('original_invoice_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('context_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('contract_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('work_unit_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('supplier_gstin', sa.String(length=20), nullable=False),
    sa.Column('recipient_gstin', sa.String(length=20), nullable=True),
    sa.Column('place_of_supply', sa.String(length=100), nullable=False),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('taxable_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_settled', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('irn', sa.String(length=100), nullable=True),
    sa.Column('ack_no', sa.String(length=50), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_document_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('issued_by', database.types.UUIDType(length=36), nullable=True),
    sa.Column('client_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['invoice_series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('irn')
    )
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_context_id'), 'invoices', ['context_id'], unique=False)
    op.create_index(op.f('ix_invoices_contract_id'), 'invoices', ['contract_id'], unique=False)
    op.create_index(op.f('ix_invoices_doc_type'), 'invoices', ['doc_type'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('deal_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('lead_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('loss_reason', sa.String(length=512), nullable=True),
    sa.Column('scope_path', sa.String(length=2048), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_client_id'), 'opportunities', ['client_id'], unique=False)
    op.create_index(op.f('ix_opportunities_deal_id'), 'opportunities', ['deal_id'], unique=False)
    op.create_index(op.f('ix_opportunities_lead_id'), 'opportunities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_opportunities_owner_user_id'), 'opportunities', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_opportunities_scope_path'), 'opportunities', ['scope_path'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('payment_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('gateway_refund_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_gateway_refund_id'), 'refunds', ['gateway_refund_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_table('billing_schedule_lines',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('schedule_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('invoice_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('milestone_type', sa.String(length=50), nullable=False),
    sa.Column('milestone_code', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['billing_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_schedule_lines_schedule_id'), 'billing_schedule_lines', ['schedule_id'], unique=False)
    op.create_table('collection_case_invoices',
    sa.Column('case_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('invoice_id', database.types.UUIDType(length=36), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['collection_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'invoice_id')
    )
    op.create_table('payment_allocations',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('payment_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('invoice_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('opportunity_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('previous_revision_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('quote_no', sa.String(length=100), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('place_of_supply', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_request_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_revision_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_client_id'), 'quotations', ['client_id'], unique=False)
    op.create_index(op.f('ix_quotations_opportunity_id'), 'quotations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_quotations_quote_no'), 'quotations', ['quote_no'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_table('contracts',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('client_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('accepted_quotation_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('opportunity_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('deal_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('parent_contract_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('contract_no', sa.String(length=100), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sla_tier', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('sla_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('coverage', sa.Text(), nullable=True),
    sa.Column('gst_fee', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_document_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_client_id'), 'contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contracts_contract_no'), 'contracts', ['contract_no'], unique=True)
    op.create_index(op.f('ix_contracts_deal_id'), 'contracts', ['deal_id'], unique=False)
    op.create_index(op.f('ix_contracts_opportunity_id'), 'contracts', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_contracts_organization_id'), 'contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('invoice_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('schedule_line_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('offering_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_line_id'], ['billing_schedule_lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('negotiation_notes',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('quotation_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('resulting_revision_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('requested_changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_revision_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_notes_quotation_id'), 'negotiation_notes', ['quotation_id'], unique=False)
    op.create_table('quotation_items',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('quotation_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('offering_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('net_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billing_model', sa.String(length=50), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('contract_payment_terms',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('contract_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('milestone_code', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('due_offset_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_payment_terms_contract_id'), 'contract_payment_terms', ['contract_id'], unique=False)
    op.create_table('contract_terms',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('contract_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('offering_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billing_model', sa.String(length=50), nullable=False),
    sa.Column('billing_frequency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_terms_contract_id'), 'contract_terms', ['contract_id'], unique=False)
    op.create_table('renewals',
    sa.Column('id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('contract_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('new_opportunity_id', database.types.UUIDType(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', database.types.UUIDType(length=36), nullable=False),
    sa.Column('outcome_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['new_opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewals_contract_id'), 'renewals', ['contract_id'], unique=False)
    op.create_index(op.f('ix_renewals_owner_user_id'), 'renewals', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_renewals_status'), 'renewals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewals_status'), table_name='renewals')
    op.drop_index(op.f('ix_renewals_owner_user_id'), table_name='renewals')
    op.drop_index(op.f('ix_renewals_contract_id'), table_name='renewals')
    op.drop_table('renewals')
    op.drop_index(op.f('ix_contract_terms_contract_id'), table_name='contract_terms')
    op.drop_table('contract_terms')
    op.drop_index(op.f('ix_contract_payment_terms_contract_id'), table_name='contract_payment_terms')
    op.drop_table('contract_payment_terms')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_index(op.f('ix_negotiation_notes_quotation_id'), table_name='negotiation_notes')
    op.drop_table('negotiation_notes')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_organization_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_opportunity_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_deal_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_no'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quote_no'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_opportunity_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_client_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_invoice_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_table('collection_case_invoices')
    op.drop_index(op.f('ix_billing_schedule_lines_schedule_id'), table_name='billing_schedule_lines')
    op.drop_table('billing_schedule_lines')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_gateway_refund_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_scope_path'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_owner_user_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lead_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deal_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_client_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_doc_type'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_contract_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_context_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_collection_followups_case_id'), table_name='collection_followups')
    op.drop_table('collection_followups')
    op.drop_index(op.f('ix_client_contacts_email'), table_name='client_contacts')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_webhook_inbox_status'), table_name='webhook_inbox')
    op.drop_index(op.f('ix_webhook_inbox_provider_event_id'), table_name='webhook_inbox')
    op.drop_index(op.f('ix_webhook_inbox_provider'), table_name='webhook_inbox')
    op.drop_table('webhook_inbox')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_receipt_no'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_offerings_vertical_id'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_organization_id'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_code'), table_name='offerings')
    op.drop_table('offerings')
    op.drop_index(op.f('ix_leads_vertical_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_scope_path'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_client_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_invoice_series_fin_registration_id'), table_name='invoice_series')
    op.drop_table('invoice_series')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_user_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_organization_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_collection_cases_status'), table_name='collection_cases')
    op.drop_index(op.f('ix_collection_cases_owner_user_id'), table_name='collection_cases')
    op.drop_index(op.f('ix_collection_cases_organization_id'), table_name='collection_cases')
    op.drop_index(op.f('ix_collection_cases_client_id'), table_name='collection_cases')
    op.drop_table('collection_cases')
    op.drop_index(op.f('ix_clients_pan'), table_name='clients')
    op.drop_index(op.f('ix_clients_owner_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_billing_schedules_status'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_organization_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_context_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_client_id'), table_name='billing_schedules')
    op.drop_table('billing_schedules')
    op.drop_index(op.f('ix_activities_subject_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_owner_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_organization_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_accounting_exports_status'), table_name='accounting_exports')
    op.drop_index(op.f('ix_accounting_exports_organization_id'), table_name='accounting_exports')
    op.drop_index(op.f('ix_accounting_exports_entity_id'), table_name='accounting_exports')
    op.drop_table('accounting_exports')
    # ### end Alembic commands ###
